version: '3.9'
services:

  wordpress:
    # default port 80
    image: wordpress:5-fpm
    container_name: wp-wordpress
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - wordpress
    depends_on:
      - database
    volumes:
      - ${WORDPRESS_LOCAL_HOME:-./build_files/wordpress}:/var/www/html
      - ${WORDPRESS_UPLOADS_CONFIG:-./config/uploads.ini}:/usr/local/etc/php/conf.d/uploads.ini
      # - /path/to/repo/myTheme/:/var/www/html/wp-content/themes/myTheme
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-database:3306}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME:-wordpress}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER:-wordpress}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD:-password123!}

  database:
    # default port 3306
    # image: mysql:8
    # container_name: wp-database
    build: 
      context: ./build_files/database
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - wordpress
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}
      - MYSQL_USER=${MYSQL_USER:-wordpress}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password123!}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword123!}
    volumes:
      - ${MYSQL_LOCAL_HOME:-./dbdata}:/var/lib/mysql
    # command:
    #   - '--default-authentication-plugin=mysql_native_password'
    ports:
      - "3306:3306"

  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    # image: nginx:1
    # container_name: wp-nginx
    build: 
      context: ./build_files/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - wordpress
    depends_on:
      - wordpress
    ports:
      - "8080:80"    # http
      # - "8443:443"   # https
    volumes:
      - ${WORDPRESS_LOCAL_HOME:-./build_files/wordpress}:/var/www/html
      - ${NGINX_CONF:-./nginx/default.conf}:/etc/nginx/http.d/default.conf
      # - ${NGINX_SSL_CERTS:-./ssl}:/etc/ssl:ro
      - ${NGINX_LOGS:-./logs/nginx}:/var/log/nginx

networks:
  wordpress:
    name: wp-wordpress
    driver: bridge